package com.model.pojo;

public class TbGkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gkey.id
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gkey.a
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    private String a;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gkey.id
     *
     * @return the value of tb_gkey.id
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gkey.id
     *
     * @param id the value for tb_gkey.id
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gkey.a
     *
     * @return the value of tb_gkey.a
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gkey.a
     *
     * @param a the value for tb_gkey.a
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    public void setA(String a) {
        this.a = a;
    }
}