package com.model.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Weight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.id
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.tracknbr
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    private String tracknbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.create_date
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.modify_date
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.id
     *
     * @return the value of weight.id
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.id
     *
     * @param id the value for weight.id
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.weight
     *
     * @return the value of weight.weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.weight
     *
     * @param weight the value for weight.weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.tracknbr
     *
     * @return the value of weight.tracknbr
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public String getTracknbr() {
        return tracknbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.tracknbr
     *
     * @param tracknbr the value for weight.tracknbr
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public void setTracknbr(String tracknbr) {
        this.tracknbr = tracknbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.create_date
     *
     * @return the value of weight.create_date
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.create_date
     *
     * @param createDate the value for weight.create_date
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.modify_date
     *
     * @return the value of weight.modify_date
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.modify_date
     *
     * @param modifyDate the value for weight.modify_date
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}