package com.model.dao;

import com.model.pojo.TbGkey;
import com.model.pojo.TbGkeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int countByExample(TbGkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int deleteByExample(TbGkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int insert(TbGkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int insertSelective(TbGkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    List<TbGkey> selectByExample(TbGkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    TbGkey selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbGkey record, @Param("example") TbGkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int updateByExample(@Param("record") TbGkey record, @Param("example") TbGkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int updateByPrimaryKeySelective(TbGkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gkey
     *
     * @mbggenerated Thu Aug 31 14:42:38 CST 2017
     */
    int updateByPrimaryKey(TbGkey record);
}