package com.model.dao;

import com.model.pojo.Weight;
import com.model.pojo.WeightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int countByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int deleteByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int insert(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int insertSelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    List<Weight> selectByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    Weight selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int updateByExample(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int updateByPrimaryKeySelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Thu Aug 31 14:19:29 CST 2017
     */
    int updateByPrimaryKey(Weight record);
}